server:
  port: 8007

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketbooking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
    # schema: classpath:schema.sql
    # data: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#   kafka:
#     consumer:
#       group-id: ticket-booking-group
#       auto-offset-reset: earliest
#     producer:
#       bootstrap-servers: localhost:9092

# Log settings
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

# Security settings (e.g., JWT, etc.)
security:
  jwt:
    secret-key: kiran12345678910111213141516171819202122232425
    expiration-time: 3600000 # 1 hour

