server:
  port: 8007

# spring:
#   datasource:
#     url: jdbc:postgresql://localhost:5432/ticketbooking
#     username: yourusername
#     password: yourpassword
#     driver-class-name: org.postgresql.Driver
#     hikari:
#       maximum-pool-size: 10

#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true

#   kafka:
#     consumer:
#       group-id: ticket-booking-group
#       auto-offset-reset: earliest
#     producer:
#       bootstrap-servers: localhost:9092

# Log settings
logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

# Security settings (e.g., JWT, etc.)
security:
  jwt:
    secret-key: kiran
    expiration-time: 3600000 # 1 hour

