server:
  port: 8007

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketbooking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
    # schema: classpath:schema.sql
    # data: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: bookingGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    redis:
      host: localhost
      port: 6379


# Log settings
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
  
  file:
    name: logs/app.log # Define the log file location
  logback:
    rollingpolicy:
      max-file-size: 1MB   # Maximum log file size before rolling
      max-history: 5        # Retain logs for 5 days
      total-size-cap: 10MB

# Security settings (e.g., JWT, etc.)
security:
  jwt:
    secret-key: kiran12345678910111213141516171819202122232425
    expiration-time: 3600000 # 1 hour

